CREATE TABLE IF NOT EXISTS `buku_tamu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama_tamu` VARCHAR(255) NOT NULL,
  `instansi` VARCHAR(255) DEFAULT NULL,
  `jabatan` VARCHAR(255) DEFAULT NULL,
  `kontak` VARCHAR(50) DEFAULT NULL,
  `kegiatan` VARCHAR(255) DEFAULT NULL,
  `keperluan` TEXT DEFAULT NULL,
  `lokasi` VARCHAR(255) DEFAULT 'Dinas Koperasi dan UKM',
  `waktu_hadir` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(50) DEFAULT 'Hadir',
  `metode` VARCHAR(50) DEFAULT 'Manual',
  `kategori` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
