CREATE TABLE IF NOT EXISTS `kib_e` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_barang` VARCHAR(100) NOT NULL,
  `nama_barang` VARCHAR(255) NOT NULL,
  `nomor_register` VARCHAR(50) DEFAULT NULL,
  `tahun_perolehan` YEAR DEFAULT NULL,
  `kondisi` VARCHAR(50) DEFAULT 'Baik',
  `harga` DECIMAL(20,2) DEFAULT 0.00,
  `keterangan` TEXT DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT 'ASET TETAP',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
